export const GETDOGS = 'GET_DOGS';
export const GETDOGBYID = 'GET_DOG_BY_ID';
export const GETDOGSBYNAME = 'GET_DOGS_BY_NAME';
export const GETTEMPERAMENT = 'GET_TEMPERAMENT';
export const FILTEREDTEMPERAMENT = 'FILTERED_TEMPERAMENT';
export const ORDER = 'ORDER';
export const CREATEDOG = 'CREATE_DOG';
export const FILTER_BY_ID_TYPE = "FILTER_BY_ID_TYPE";